name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: read 
  contents: write 
  id-token: write 
  packages: write
  pages: write


concurrency:
  # Only allows one build per workflow & branch/PR/tag
  # cancels in-progress builds for that branch/PR/tag if a new one is submitted
  # https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: pathi-cloud/github-workflows/.github/workflows/ci-ui-application.yml@main
    with:
      run_acceptance: false
      gh_pages_deploy_dir: ./build-ghpages
  
  docker:
    needs:
      - ci
    uses: pathi-cloud/github-workflows/.github/workflows/ci-container-ghcr.yml@main
    secrets: inherit
    with:
      tag_version: 1.0
      ghcr_repo: 'tasks-app'
